### ISSUE TITLE
Fix the compressed image remaps...

### ISSUE THREAD

**Issue by DominicD-823543** [QVPR/teach-repeat#20]

**Comment by Tobias-Fischer** [comment]
@DominicD-823543 - what exactly needs fixing?

**Comment by DominicD-823543** [comment]
I can't remember what I meant here actually. I think it might have been to do with allowing the use of compressed images on the Jackal, but if we run it onboard it's not a big issue anyway I guess, because we can't use `image_transport` in python?

**Comment by Tobias-Fischer** [comment]
It's running all fine onboard, so let's close this.
