### ISSUE TITLE
Will package work with Husky simulator?

### ISSUE THREAD

**Issue by Russ76** [QVPR/teach-repeat#26]
I don't have a jackal robot but I can easily get the Husky simulator. Will this software work with Husky? We don't really need any of the jackal package, do we?

**Comment by Tobias-Fischer** [comment]
Hi @Russ76 - yes, the package is robot agnostic. Simply modify the `data_collection_jackal.launch` to point towards existing odometry and image topics. Also I think you need to create the `save_dir` specified in the launch file. Similarly, for the repeat run, modify `data_matching_jackal.launch`. You might want to adjust `min_omega`, `max_omega` and `max_v`.
