### ISSUE TITLE
Mono camera or stereo camera?

### ISSUE THREAD

**Issue by Russ76** [QVPR/teach-repeat#33]
The readme file says a mono camera is required, but the nodes all work with stereo camera images! I have the Intel D435 so it has stereo images. On what topics should it publish? Its stereo output is black and white already.

**Comment by Tobias-Fischer** [comment]
Our system works with monocular images (I'm not sure what you mean by "all the nodes". The only node that requires stereo images is the image stitcher for the MiRo, which combines them into a stitched image. See the Jackal launch files for a monocular setup:
https://github.com/QVPR/teach-repeat/blob/master/launch/data_collection_jackal.launch
https://github.com/QVPR/teach-repeat/blob/master/launch/data_matching_jackal.launch

(i.e. the image topic is remapped to "image".)

Feel free to reopen if you have more questions.
