### ISSUE TITLE
Repeat phase throws error

### ISSUE THREAD

**Issue by Russ76** [QVPR/teach-repeat#34]
RLException: [/home/uriah/catkin_ws/src/teach-repeat/launch/data_matching_jackal.launch] requires the 'odom_corruption_factor' arg to be set

Is this a true/false? Or is it a number? Is it contained in the data files saved by data_collection phase?

I see that the name of the proper date folder must be edited into the launch file. That is done.

This is on a real robot, not sim.

**Comment by Dominic-DallOsto** [comment]
Does setting `use_corrupted_odom` fix the error for you? Otherwise setting `odom_corruption_factor` to 1.0 should also cause no corruption of odometry readings.

**Comment by Russ76** [comment]
Will try that soon, thanks!

**Comment by Tobias-Fischer** [comment]
Same as #35
